name: Deploy Vue
on:
  push:
    branches:
      - master
jobs:
  release-on-push:
    release-on-push:
    name: Tag Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@0.25.0
        with:
          bump_version_scheme: minor
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "vaibhav101"
          reponame: "vaibhav101.github.io"
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
